#!/usr/bin/env python3
"""Rewrite dvisvgm output so its colours follow the site's light/dark tokens.

The .tex draws each semantic role in a sentinel hex (#FF00xx). Here every
sentinel becomes `fill='<light hex>' class='fig-xx'`: the hex is a sane
fallback if the stylesheet never loads, and the class rule (CSS beats a
presentation attribute) is what actually paints it, so the figure follows
:root[data-theme] and prefers-color-scheme exactly like the rest of the page.

Also strips the fixed pt width/height so the SVG scales with its container,
and splices the result into Research.md between the generated-block markers.
"""
import re
import sys
from pathlib import Path

# sentinel -> (css class, light fallback hex). The triangle edges arrive as a
# stroke, everything else as a fill, so each sentinel is rewritten in whichever
# attribute dvisvgm actually used.
ROLES = {
    "#ff0001": ("fig-cs",   "#147F8A"),
    "#ff0002": ("fig-is",   "#DA1884"),
    "#ff0003": ("fig-ah",   "#9A6B12"),
    "#ff0004": ("fig-core", "#DA1884"),
    "#ff0005": ("fig-edge", "#A9A6A0"),
    "#ff0006": ("fig-ink",  "#1C1C1C"),
    "#ff0007": ("fig-bg",   "#FFFDF9"),
}

# Mirrors the three-way convention in _layout/style.html: base :root, an
# explicit [data-theme="dark"], and OS-dark for users who never touched
# the toggle. Values are the site tokens, hard-coded so the figure still
# themes correctly if it is ever opened as a standalone file.
THEME_CSS = """
.fig-triangle {
  display: block;
  width: 100%;
  max-width: 460px;
  height: auto;
  margin: 2.4em auto 1.2em;
  --fig-cs: #147F8A;
  --fig-is: #DA1884;
  --fig-ah: #9A6B12;
  --fig-core: #DA1884;
  --fig-line: rgba(28,28,28,0.35);
  --fig-ink: #1C1C1C;
  --fig-bg: #FFFDF9;
}
:root[data-theme="dark"] .fig-triangle {
  --fig-cs: #43C4CE;
  --fig-is: #F062AE;
  --fig-ah: #C9B072;
  --fig-core: #F062AE;
  --fig-line: rgba(233,237,236,0.32);
  --fig-ink: #E9EDEC;
  --fig-bg: #16292A;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) .fig-triangle {
    --fig-cs: #43C4CE;
    --fig-is: #F062AE;
    --fig-ah: #C9B072;
    --fig-core: #F062AE;
    --fig-line: rgba(233,237,236,0.32);
    --fig-ink: #E9EDEC;
    --fig-bg: #16292A;
  }
}
.fig-triangle .fig-cs   { fill: var(--fig-cs); }
.fig-triangle .fig-is   { fill: var(--fig-is); }
.fig-triangle .fig-ah   { fill: var(--fig-ah); }
.fig-triangle .fig-core { fill: var(--fig-core); }
.fig-triangle .fig-ink  { fill: var(--fig-ink); }
.fig-triangle .fig-bg   { fill: var(--fig-bg); }
.fig-triangle .fig-edge { stroke: var(--fig-line); }
"""

TITLE = "The three fields my research sits between"
DESC = (
    "A triangle whose corners are Complex Systems, Information Sciences, and "
    "Arts and Humanities. Each edge is labelled with the work that joins the two "
    "fields it connects: semi-automated cataloging and knowledge discovery between "
    "Complex Systems and Information Sciences, cultural evolution between Complex "
    "Systems and Arts and Humanities, and digital humanities between Information "
    "Sciences and Arts and Humanities."
)

BEGIN = "<!-- BEGIN research-triangle (generated by figures/tikz/build.sh — do not edit) -->"
END = "<!-- END research-triangle -->"


def theme(svg: str) -> str:
    for sentinel, (cls, fallback) in ROLES.items():
        # <path fill='#ff0001'/>, <tspan fill='#ff0001'>, <path stroke='#ff0005'>
        for attr in ("fill", "stroke"):
            svg = svg.replace(f"{attr}='{sentinel}'",
                              f"{attr}='{fallback}' class='{cls}'")
    if re.search(r"#ff000\d", svg, re.I):
        sys.exit("error: unmapped sentinel colour left in the SVG")

    # scale with the container instead of a fixed pt box; keep the viewBox
    svg = re.sub(r"\s+width='[^']*pt'\s+height='[^']*pt'", "", svg, count=1)
    svg = svg.replace(
        "<svg version='1.1'",
        "<svg version='1.1' class='fig-triangle' role='img' "
        "aria-labelledby='rt-title rt-desc'",
        1,
    )
    svg = svg.replace(
        ">\n<style type='text/css'>",
        f">\n<title id='rt-title'>{TITLE}</title>\n<desc id='rt-desc'>{DESC}</desc>\n"
        "<style type='text/css'>",
        1,
    )
    # append the theme rules to dvisvgm's own <style> (it holds the @font-face)
    return svg.replace("]]>\n</style>", THEME_CSS + "]]>\n</style>", 1)


def splice(page: Path, svg: str) -> None:
    text = page.read_text()
    block = f"{BEGIN}\n~~~\n<figure class=\"fig-figure\">\n{svg.strip()}\n</figure>\n~~~\n{END}"
    if BEGIN in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block,
                      text, flags=re.S)
        page.write_text(text)
        print(f"spliced into {page}")
    else:
        print(f"markers not found in {page}; insert this block manually:\n{BEGIN}")


if __name__ == "__main__":
    raw, out, page = (Path(a) for a in sys.argv[1:4])
    # drop the XML prolog and the dvisvgm comment: this markup gets inlined
    body = re.sub(r"^<\?xml[^>]*\?>\s*|^<!--.*?-->\s*", "", raw.read_text(), flags=re.M)
    themed = theme(body)
    out.write_text(themed)
    print(f"wrote {out} ({len(themed)} bytes)")
    splice(page, themed)
